apiVersion: batch/v1
kind: Job
metadata:
  name: broadcast
spec:
  backoffLimit: 1
  parallelism: 9  # 9 pods scheduled concurrenctly
  template:
    metadata:
      labels:
        app: broadcast
    spec:
      nodeSelector:
        nodetype: broadcast
      restartPolicy: Never
      volumes:
      - name: google-cloud-key
        secret:
          secretName: pubsub-key
      containers:
      - name: broadcast
        image: jonasspenger/tamperproofbroadcast
        command: ["/bin/sh", "-c"]
        args:
        - echo running benchmark;
          python3 tamperproofbroadcast/tests/benchmarks/benchmark.py --duration 60 --testid 12-etcd-$(hostname) --etcdhost etcd.default.svc.cluster.local --etcdport 2379;
          echo finished benchmark;
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
