apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: multichain
spec:
  serviceName: multichain
  replicas: 3
  selector:
    matchLabels:
      app: multichain
  template:
    metadata:
      labels:
        app: multichain
    spec:
      nodeSelector:
        nodetype: multichain
      containers:
      - name: multichain
        image: alpine
        ports:
        - containerPort: 7209
        - containerPort: 7208
        command: ["/bin/sh", "-c"]
        args:
        - echo setting up environment;
          echo installing etcdctl;
          echo "@testing http://nl.alpinelinux.org/alpine/edge/testing" | tee -a /etc/apk/repositories;
          apk add --update etcd-ctl@testing;
          echo ;
          echo installing multichain;
          wget --quiet https://www.multichain.com/download/multichain-2.0.5.tar.gz;
          tar -xvzf multichain-2.0.5.tar.gz;
          cd multichain-2.0.5;
          mv multichaind multichain-cli multichain-util /usr/local/bin;
          echo ;
          echo connecting multichain blockchain;
          if [[ "$(etcdctl --endpoints=etcd.default.svc.cluster.local:2379 put --prev-kv multichain started)" == "OK" ]];
          then echo creating a new blockchain;
          multichain-util create chain -anyone-can-connect=true -anyone-can-send=true -anyone-can-receive=true -anyone-can-mine=true -target-block-time=10 -first-block-reward=1 -mining-turnover=1.0 -default-network-port=7209 -default-rpc-port=7208 -mine-empty-rounds=1000000000	-initial-block-reward=1000000000;
          echo running a new blockchain;
          multichaind chain -rpcuser=user -rpcpassword=password -rpcport=7208 -network-port=7209 -rpcallowip=0.0.0.0/0.0.0.0;
          else echo joining an existing blockchain;
          multichaind chain@$(getent hosts multichain | cut -d' ' -f1):7209 -rpcuser=user -rpcpassword=password -rpcport=7208 -network-port=7209 -rpcallowip=0.0.0.0/0.0.0.0;
          fi;
---
apiVersion: v1
kind: Service
metadata:
  name: multichain
spec:
  selector:
    app: multichain
  ports:
    - name: multichainpeer
      port: 7209
      targetPort: 7209
    - name: multichainclient
      port: 7208
      targetPort: 7208
---
apiVersion: v1
kind: Service
metadata:
  name: multichain-headless
spec:
  selector:
    app: multichain
  clusterIP: None
  ports:
    - name: multichainpeer
      port: 7209
      targetPort: 7209
    - name: multichainclient
      port: 7208
      targetPort: 7208
